kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{ include "accessibility.labels" . | nindent 4 }}
data:
  {{ include "validate-configuration" . }}
  {{ $configuration := index .Values.configurations .Values.configuration }}

  {{ if $configuration.configMapData }}
  {{ toYaml $configuration.configMapData | nindent 2 }}
  {{ end }}
