apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  hosts:
    # Match on in-cluster traffic with short hostname
    - {{ .Release.Name | quote }}
    # Match on in-cluster traffic with FQDN
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
  {{- include "validate-configuration" $ }}
  {{- $configuration := index .Values.configurations .Values.configuration -}}
  {{- $defaultIstioGateway := "istio-system/g5devops" }}
    # configuration was: {{ required "configuration is required" .Values.configuration }}
    # environment was: {{ required "environment is required" .Values.environment }}
  {{- $defaultPublicHostname := printf "%s-%s.g5devops.com" .Release.Name .Values.environment -}}

  {{- if eq .Values.configuration "production" -}}
    {{- $defaultIstioGateway = "istio-system/g5marketingcloud" -}}
    {{- $defaultPublicHostname = printf "%s.g5marketingcloud.com" .Release.Name -}}
  {{- end }}

    # Match on Internet traffic
    - {{ $configuration.publicHostname | default $defaultPublicHostname | quote }}
  gateways:
    - {{ $configuration.istioGateway | default $defaultIstioGateway | quote }}
  http:
  - route:
    - destination:
        port:
          number: 80
        host: {{ .Release.Name | quote }}